platform :ios, '6.0'
pod 'AFNetworking',	  '~> 1.3.1'
pod 'AFHTTPRequestOperationLogger',	'~> 0.10.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'OHHTTPStubs', '2.0.0'
pod 'MagicalRecord', '2.2'
pod 'FMDB', '2.1'
pod 'SDWebImage', '3.5'
pod 'JMImageCache', '0.4.0'
pod 'NSDate+TimeAgo'
pod 'MKNetworkKit'
pod 'FDTake', '0.1'
pod 'GoogleAnalytics-iOS-SDK', '3.0.2'
pod 'FlurrySDK', '4.3.0'
