platform :ios, '7.0'
pod 'AFNetworking',	  '~> 1.3.1'
pod 'AFHTTPRequestOperationLogger',	'~> 0.10.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'OHHTTPStubs', '2.0.0'
pod 'MagicalRecord', '2.2'
pod 'FMDB', '2.1'
pod 'SDWebImage', '3.7.1'
pod 'JMImageCache', '0.4.0'
pod 'NSDate+TimeAgo'
pod 'MKNetworkKit'
pod 'GoogleAnalytics-iOS-SDK', '3.0.6'
pod 'FlurrySDK', '4.3.0'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'SocketRocket', '~> 0.3.1-beta2'
pod 'CocoaLumberjack', '~> 2.0.0-beta4'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'FESSolarCalculator'
pod 'SimulatorRemoteNotifications', '~> 0.0.2'
pod 'UICKeyChainStore', '~> 1.0'
pod 'NYXImagesKit', '~> 2.3'
pod 'Facebook-iOS-SDK', '3.19'
pod 'FXPageControl', '1.3.2'
pod 'TAPKeyboardPop', '~> 0.1.2'
pod 'GPUImage'
pod "URBMediaFocusViewController"
pod 'pop', '~> 1.0'
pod 'FXBlurView'
pod 'YLProgressBar', '~> 3.5.2'
pod 'SwipeView'
pod 'JTSImageViewController'
